# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Panda sites
email: duked.yang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Panda images you may like, and upload photoes taken in China Chengdu.
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
github_username:
github_appreciate: Adagio-cantabile

# Gems settings
plugins: [jekyll-paginate]

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate: 5
